# Generated by Django 5.2 on 2025-04-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GLOBAL', 'Global'), ('INDIA', 'India')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('text', models.TextField()),
                ('top_image', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='newsapp.region')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sentiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='newsapp.sentiment'),
        ),
    ]
