# Generated by Django 5.2 on 2025-04-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('US', 'US'), ('INDIA', 'India')], max_length=20, unique=True),
        ),
    ]
